#!/bin/sh

# Initially create all:
#
#aclocal
#autoheader
#autoreconf
#automake --add-missing
#libtoolize

# At each reconfiguration:
#
make distclean
autoreconf
./configure --prefix=$HOME
make

# Before checking in to git: don't forget to update the port.
# make dist
# cp mrksvnup-0.1.tar.gz /usr/data/distfiles
# cd /usr/data/distfiles && git commit a -m update && git push
# cd ports && make makesum
