#!/bin/sh

# Initially create all:
#
#aclocal
#autoheader
#autoreconf
#automake --add-missing
#libtoolize

# At each reconfiguration:
#
make distclean
autoreconf
./configure --prefix=$HOME --enable-fcolor --enable-debug
make

# Before checking in to git: don't forget to update the port.
# # autoreconf
# # make dist
# # cp mrksvnup-0.1.tar.gz /usr/data/distfiles
# # cd /usr/data/distfiles && git commit a -m update && git push
# # cd ports && [manually make sum from /usr/data/distfiles/mrksvnup-0.1.tar.gz]          
