# $FreeBSD$
PORTNAME=	mrksvnup
PORTVERSION=	0.1
CATEGORIES=	net
MASTER_SITES=	https://raw.github.com/mkushnir/distfiles/master/

MAINTAINER=	markiyan.kushnir@gmail.com
COMMENT=	A fast svnup for FreeBSD

#MAN1=		svnup.1
#MANCOMPRESSED=	yes
USE_LDCONFIG=	yes

# I assume it will be there
#LIB_DEPENDS=	mrkcommon:devel/mrkcommon

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
